services:
  fastapi-app:
    build: .
    container_name: backend-mesh-service
    ports:
      - "8000:8000"
    volumes:
      - app_db_volume:/app/data
    depends_on:
      ollama-init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - mesh-network

  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama-cpu-engine
    ports:
      - "11434:11434"
    volumes:
      - model_storage_volume:/root/.ollama
    restart: unless-stopped
    networks:
      - mesh-network

  ollama-init:
    image: curlimages/curl:latest
    depends_on:
      - ollama-service
    entrypoint: >
      sh -c "
      until curl -s http://ollama-cpu-engine:11434/api/tags; do echo 'waiting for ollama...'; sleep 2; done;
      curl -X POST http://ollama-cpu-engine:11434/api/pull -d '{\"name\": \"llama3.2\"}';
      "
    networks:
      - mesh-network

networks:
  mesh-network:
    driver: bridge

volumes:
  app_db_volume:
    name: app_db_volume
  model_storage_volume:
    name: model_storage_volume